### ISSUE TITLE
[geometry] https://drafts.fxtf.org/geometry/ is stale

### ISSUE THREAD

**Issue by zcorpan** [w3c/fxtf-drafts#212]
https://drafts.fxtf.org/geometry-1/ is up to date.

https://drafts.fxtf.org/geometry/ is stale, and says "W3C Working Draft".

Why? People are using the sans -1 version and expect it to reflect current master.

https://github.com/w3c/fxtf-drafts/tree/master/geometry does not contain an Overview.html file.

@plinss can you help?

**Comment by plinss** [comment]
I fixed this last week, AFAICT it's working properly now.

**Comment by zcorpan** [comment]
Ah yes! It turned out I was still getting a cached version of the old document. Thank you for fixing, and sorry for unnecessarily bugging you about this again.
